export const icons = {
  home: require("../assets/home.png"),
  subscription: require("../assets/subscription.png"),
  insights: require("../assets/insights.png"),
  settings: require("../assets/settings.png"),
  netflix: require("../assets/netflix.png"),
  spotify: require("../assets/spotify.png"),
  hulu: require("../assets/hulu.png"),
  adobe: require("../assets/adobe.png"),
  youtube: require("../assets/youtube.png"),
  amazon: require("../assets/amazon.png"),
  dropbox: require("../assets/dropbox.png"),
  appleMusic: require("../assets/apple-music.png"),
  google: require("../assets/google.png"),
  figma: require("../assets/figma.png"),
  medium: require("../assets/medium.png"),
};
